/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package paysys;
import paysys.PaySys_Login;
import PaySys_Classes.Overtime;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.Timer;
/**
/**
 *
 * @author Giann Gernale
 */
public class PaySys_Overtime extends javax.swing.JFrame {
    int EmployeeID = Integer.parseInt(PaySys_Login.password);
    private String SCHEMA = "payrollsystem_db"; // Replace with your schema name
    private String TABLE = "`overtime`"; // Replace with your table name
    private String USER = "root"; // Replace with your database username
    private String PASSWORD = "user123"; // Replace with your database password
    DefaultTableModel model = new DefaultTableModel();
    private Timer refreshTimer;
    /**
     * Creates new form PaySys_Overtime
     */
    public PaySys_Overtime() {
        initComponents();
        model.setColumnIdentifiers(new String[]{"EmployeeID", "OvertimeStatus", "OvertimeDate", "OvertimeHours"});
        try {
            displayOvertimeDetails(jTable1);
        } catch (SQLException | ClassNotFoundException e) {
            e.printStackTrace();
        }
        refreshTimer = new Timer(5000, e -> refreshTableData()); // Refresh every 5 seconds
        refreshTimer.start();
        
    }
      public void displayOvertimeDetails(JTable jTable1) throws SQLException, ClassNotFoundException {
        Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/" + SCHEMA, USER, PASSWORD);
        Statement statement = connection.createStatement();

        // Prepare a query to fetch all columns except leaveID
        String sql = "SELECT EmployeeID, OvertimeStatus, OvertimeDate, OvertimeHours FROM " + TABLE;
        ResultSet resultSet = statement.executeQuery(sql);

        // Add rows from the result set
        while (resultSet.next()) {
            Object[] row = new Object[resultSet.getMetaData().getColumnCount()];
            for (int i = 1; i <= resultSet.getMetaData().getColumnCount(); i++) {
                row[i - 1] = resultSet.getObject(i);
            }
            model.addRow(row);
        }

        // Set the table model for the JTable
        jTable1.setModel(model);

        // Close the connection
        connection.close();
    }

    private void displayTable(JTable jTable) {
        jTable1.setModel(model);
    }

    private void setResizeTable() {
        jTable1.setAutoResizeMode(jTable1.AUTO_RESIZE_OFF);
    }

    private void refreshTableData() {
        try {
            model.setRowCount(0); // Clear existing data
            displayOvertimeDetails(jTable1);
        } catch (SQLException | ClassNotFoundException e) {
            e.printStackTrace();
        }
    }

    private boolean isValidLeaveDates(Date startDate) {
        // Check if start date is before today
        Date today = new Date();
        return !startDate.before(today);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        usernametext = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        overtimeDate = new com.toedter.calendar.JCalendar();
        overtimehour = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel24 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Overtime Request");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(729, 591));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        usernametext.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        usernametext.setForeground(new java.awt.Color(0, 0, 102));
        usernametext.setText("Employee Username");
        jPanel1.add(usernametext, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 2, -1, 50));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setText("Overtime Hours");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 455, -1, 30));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 102, 0));
        jButton1.setText("Apply");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 540, 110, -1));

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(102, 0, 0));
        jButton2.setText("Close");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 540, 110, -1));
        jPanel1.add(overtimeDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 500, 380));

        overtimehour.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        overtimehour.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));
        jPanel1.add(overtimehour, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, 140, 22));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setGridColor(new java.awt.Color(0, 0, 102));
        jScrollPane3.setViewportView(jTable1);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 60, 420, 510));

        jLabel24.setText("© 2024 MotorPH Co., All Rights Reserved. ");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 610, -1, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         // TODO add your handling code here:
        Overtime overtime= new Overtime();
        Date OvertimeDate = overtimeDate.getDate();
        String overtimeStatus = "Pending";
        int overtimeHours = Integer.parseInt(overtimehour.getSelectedItem().toString());

        // Check for invalid dates
        if (!isValidLeaveDates(OvertimeDate)) {
            JOptionPane.showMessageDialog(null, "Invalid overtime dates. Please ensure the overtime date is after today.", "Error", JOptionPane.ERROR_MESSAGE);
            return; // Exit the method if dates are invalid
        }

        try {
            overtime.setOvertimeDetails(EmployeeID, OvertimeDate, overtimeStatus, overtimeHours);
            overtime.recordOvertime(); // Call recordLeave method after setting details
            // Display success message (optional)
            JOptionPane.showMessageDialog(null, "Overtime application submitted!", "Success", JOptionPane.INFORMATION_MESSAGE);
        } catch (SQLException | ClassNotFoundException | ParseException ex) {
            // Handle database errors and ParseException (optional)
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Error submitting overtime application: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
        
        jButton1.setEnabled(false);
        
        Timer timer = new Timer(180000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent evt) {
                jButton1.setEnabled(true);
            }
        });

        // Set the timer to execute only once
        timer.setRepeats(false);

        // Start the timer
        timer.start();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PaySys_Overtime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PaySys_Overtime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PaySys_Overtime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PaySys_Overtime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PaySys_Overtime().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private com.toedter.calendar.JCalendar overtimeDate;
    private javax.swing.JComboBox<String> overtimehour;
    public javax.swing.JLabel usernametext;
    // End of variables declaration//GEN-END:variables
}
